### ISSUE TITLE
guardian: set seed - make it onlyOwner

### ISSUE THREAD

**Issue by tuxcanfly** [the-torn/floot#2]
Currently the guardian cannot be different from the owner of the contract. Wouldn't it be better to make `setGuardianSeed` `onlyOwner` keeping this in mind?

**Comment by the-torn** [comment]
Access control is not needed on `setGuardianSeed` since the value is validated against the `GUARDIAN_HASH` that was committed when the contract was deployed.

The contract is not `Ownable`. There is no contract owner, although the contract deployer effectively chooses the guardian by way of the `GUARDIAN_HASH`.

**Comment by tuxcanfly** [comment]
Oh nice, I didn't realize  that.
